#!/bin/sh

if [ "$#" -ne 3 ]; then
  echo ""
  echo "Usage: ./projectrunscript <suite> <benchmark> <repl_policy>"
  echo "    (suite) benchmarks: "
  echo "      -- (SPEC) bzip2 gcc mcf hmmer sjeng libquantum xalan milc cactusADM leslie3d namd soplex calculix lbm"
  echo "      -- (PARSEC) blackscholes bodytrack canneal dedup fluidanimate freqmine streamcluster swaptions x264"
  echo "    repl_policy: LRU LFU SRRIP SHiP"
else
  suite=$1
  bench=$2
  repl=$3

  # your simulation results will be saved to outputs/project/$repl/$bench/
  if [ "$suite" = "SPEC" ]; then
    mkdir -p outputs/project/$repl/${bench}
    echo "./build/opt/zsim configs/project/$repl/${bench}.cfg > outputs/project/$repl/${bench}/${bench}.log 2>&1"
    ./build/opt/zsim configs/project/$repl/${bench}.cfg >outputs/project/$repl/${bench}/${bench}.log 2>&1
  elif [ "$suite" = "PARSEC" ]; then
    mkdir -p outputs/project/$repl/${bench}_8c_simlarge
    echo "./build/opt/zsim configs/project/$repl/${bench}_8c_simlarge.cfg > outputs/project/$repl/${bench}_8c_simlarge/${bench}.log 2>&1"
    ./build/opt/zsim configs/project/$repl/${bench}_8c_simlarge.cfg >outputs/project/$repl/${bench}_8c_simlarge/${bench}.log 2>&1
  else
    echo "No such benchmark suite, please specify SPEC or PARSEC"
  fi
fi
